// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUE50xdLKAEWHEYlPidazD5JtZnTWvivE',
    appId: '1:239239555207:web:ace0399de8d606bba2f022',
    messagingSenderId: '239239555207',
    projectId: 'fir-1st-3da49',
    authDomain: 'fir-1st-3da49.firebaseapp.com',
    storageBucket: 'fir-1st-3da49.firebasestorage.app',
    measurementId: 'G-EBJCWDVTPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVmtpthHqXkai4wZrkcMPaoAfD-aoEHgU',
    appId: '1:239239555207:android:3bbac7e3df6a28e5a2f022',
    messagingSenderId: '239239555207',
    projectId: 'fir-1st-3da49',
    storageBucket: 'fir-1st-3da49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuHX1Pm6M8dS80tASZKHRs4aYyCeYcH3I',
    appId: '1:239239555207:ios:1fc9a6784b05dfa2a2f022',
    messagingSenderId: '239239555207',
    projectId: 'fir-1st-3da49',
    storageBucket: 'fir-1st-3da49.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuHX1Pm6M8dS80tASZKHRs4aYyCeYcH3I',
    appId: '1:239239555207:ios:1fc9a6784b05dfa2a2f022',
    messagingSenderId: '239239555207',
    projectId: 'fir-1st-3da49',
    storageBucket: 'fir-1st-3da49.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUE50xdLKAEWHEYlPidazD5JtZnTWvivE',
    appId: '1:239239555207:web:d07bdd8b0064b5f2a2f022',
    messagingSenderId: '239239555207',
    projectId: 'fir-1st-3da49',
    authDomain: 'fir-1st-3da49.firebaseapp.com',
    storageBucket: 'fir-1st-3da49.firebasestorage.app',
    measurementId: 'G-DN668FRDJG',
  );
}
